/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Parvez
 */
public class RecpPatientPanelUpdate extends javax.swing.JFrame {

    int patientListNumber = 0, c = 0,nn=-1;
    List<Patient> plist = new ArrayList<Patient>();

    /**
     * Creates new form PatientPanel
     */
    public RecpPatientPanelUpdate() {
        initComponents();
        NumberRead nr = new NumberRead();
    patientListNumber = nr.tableintrecp();
        if (patientListNumber != -1) {
            set();
        }
    }
 public void set() {
     List<Receptionist> list = new ArrayList<Receptionist>();
        NumberRead num = new NumberRead();
        nn = num.read();
        FileRead fwa = new FileRead();
        list = fwa.fileReadReceptionist();
        name.setText(list.get(nn).getName());
        FileRead fw = new FileRead();

        plist = fw.fileReadPatient();
        jUserName.setText(plist.get(patientListNumber).getUsername());
        jPassword.setText(plist.get(patientListNumber).getPassword());
        jFullName.setText(plist.get(patientListNumber).getName());
        jAge.setText(plist.get(patientListNumber).getAge());
        jGenderCombo.setSelectedItem(plist.get(patientListNumber).getGender());
        jAddress.setText(plist.get(patientListNumber).getAddress());
        jMaritialCombo.setSelectedItem(plist.get(patientListNumber).getMaritial());
        jPhoneNo.setText(plist.get(patientListNumber).getPhone());
        jPatientTypeCombo.setSelectedItem(plist.get(patientListNumber).getPatientType());
        jBloodGroupCombo.setSelectedItem(plist.get(patientListNumber).getBlood());
        jDate.setDate(plist.get(patientListNumber).getDate());
        NumberWrite nwe = new NumberWrite();
        nwe.tableint(-1);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jFullName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jAge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jGenderCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jMaritialCombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPhoneNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPatientTypeCombo = new javax.swing.JComboBox<>();
        jUpdateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSearch = new javax.swing.JTextField();
        jSearchButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jBloodGroupCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        add5 = new javax.swing.JLabel();
        update4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        update5 = new javax.swing.JLabel();
        update6 = new javax.swing.JLabel();
        update7 = new javax.swing.JLabel();
        update8 = new javax.swing.JLabel();
        update9 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(24, 44, 97));

        jLabel8.setBackground(new java.awt.Color(0, 204, 204));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Patient Details");

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hms60.png"))); // NOI18N
        jLabel1.setText("HMS");

        name.setEditable(false);
        name.setBackground(new java.awt.Color(24, 44, 97));
        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        name.setText("Abdul Wahid");
        name.setBorder(null);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(232, 65, 24));
        jLabel15.setText("(Logout)");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Full Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 30));

        jFullName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel1.add(jFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 198, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 30));

        jAge.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel1.add(jAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 72, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 409, -1, 30));

        jGenderCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jGenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Other" }));
        jPanel1.add(jGenderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 459, -1, 30));

        jAddress.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel1.add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 459, 483, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel11.setText("Marital status ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 509, -1, 30));

        jMaritialCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jMaritialCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Marrired", "Unmarried" }));
        jPanel1.add(jMaritialCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 509, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel14.setText("Phone No.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, -1, 30));

        jPhoneNo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel1.add(jPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 175, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel12.setText("Date");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel13.setText("Patient Type");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, -1, 30));

        jPatientTypeCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jPatientTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Indoor", "Outdoor" }));
        jPanel1.add(jPatientTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, -1, 30));

        jUpdateButton.setBackground(new java.awt.Color(6, 82, 221));
        jUpdateButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 680, 180, 55));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Enter Patient name to Update");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 259, -1));

        jSearchButton.setBackground(new java.awt.Color(6, 82, 221));
        jSearchButton.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        jSearchButton.setText("Find");
        jSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel18.setText("Blood Group");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 710, -1, 30));

        jBloodGroupCombo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBloodGroupCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        jPanel1.add(jBloodGroupCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 720, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 209, -1, -1));

        jUserName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel1.add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 209, 198, -1));

        jPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 200, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, 30));

        jPanel13.setBackground(new java.awt.Color(24, 44, 97));

        add5.setBackground(new java.awt.Color(0, 204, 204));
        add5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        add5.setForeground(new java.awt.Color(255, 255, 255));
        add5.setText("Appointments");
        add5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add5addMouseClicked(evt);
            }
        });

        update4.setBackground(new java.awt.Color(0, 204, 204));
        update4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        update4.setForeground(new java.awt.Color(255, 255, 255));
        update4.setText("Edit Profile");
        update4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update4updateMouseClicked(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        update5.setBackground(new java.awt.Color(0, 204, 204));
        update5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        update5.setForeground(new java.awt.Color(255, 255, 255));
        update5.setText("Add Patient");
        update5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update5updateMouseClicked(evt);
            }
        });

        update6.setBackground(new java.awt.Color(0, 204, 204));
        update6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        update6.setForeground(new java.awt.Color(255, 255, 255));
        update6.setText("Update Patient");
        update6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update6updateMouseClicked(evt);
            }
        });

        update7.setBackground(new java.awt.Color(0, 204, 204));
        update7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        update7.setForeground(new java.awt.Color(255, 255, 255));
        update7.setText("Remove Patient");
        update7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update7updateMouseClicked(evt);
            }
        });

        update8.setBackground(new java.awt.Color(0, 204, 204));
        update8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        update8.setForeground(new java.awt.Color(255, 255, 255));
        update8.setText("Patients list");
        update8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update8updateMouseClicked(evt);
            }
        });

        update9.setBackground(new java.awt.Color(0, 204, 204));
        update9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        update9.setForeground(new java.awt.Color(255, 255, 255));
        update9.setText("Search Patient");
        update9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update9updateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(add5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(update6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(update9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(add5)
                .addGap(31, 31, 31)
                .addComponent(update5)
                .addGap(35, 35, 35)
                .addComponent(update7)
                .addGap(28, 28, 28)
                .addComponent(update9)
                .addGap(34, 34, 34)
                .addComponent(update6)
                .addGap(5, 5, 5)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update8)
                .addGap(33, 33, 33)
                .addComponent(update4)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, -1, 650));

        jDate.setDateFormatString("d MMM, yyyy");
        jDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanel1.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 147, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchButtonActionPerformed
        String find = jSearch.getText();
        FileRead fw = new FileRead();
        clear();
        plist = fw.fileReadPatient();
        int i = -1;
        c = 0;
        for (Patient dc : plist) {
            i++;
            if (find.equalsIgnoreCase(dc.getName())) {
                c = 1;
                break;
            }

        }
        if (c == 0) {
            JOptionPane.showMessageDialog(null, "No Data Found",
                    "ERROR", JOptionPane.WARNING_MESSAGE);
            clear();
            patientListNumber=-1;

        } else {
            jUserName.setText(plist.get(i).getUsername());
            jPassword.setText(plist.get(i).getPassword());
            jFullName.setText(plist.get(i).getName());
            jAge.setText(plist.get(i).getAge());
            jGenderCombo.setSelectedItem(plist.get(i).getGender());
            jAddress.setText(plist.get(i).getAddress());
            jMaritialCombo.setSelectedItem(plist.get(i).getMaritial());
            jPhoneNo.setText(plist.get(i).getPhone());
            jBloodGroupCombo.setSelectedItem(plist.get(i).getBlood());
            jPatientTypeCombo.setSelectedItem(plist.get(i).getPatientType());
            jDate.setDate(plist.get(i).getDate());
            patientListNumber = i;
        }
    }//GEN-LAST:event_jSearchButtonActionPerformed
    public void clear() {
        jSearch.setText("");
        jUserName.setText("");
        jPassword.setText("");
        jFullName.setText("");
        jAge.setText("");
        jGenderCombo.setSelectedItem("Select");
        jAddress.setText("");
        jMaritialCombo.setSelectedItem("Select");
        jPhoneNo.setText("");
        jBloodGroupCombo.setSelectedItem("Select");
        jPatientTypeCombo.setSelectedItem("Select");
        jDate.setDate(null);
    }
    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSearchActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        LoginAsFrame al = new LoginAsFrame();
        al.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        if (jUserName.getText().isEmpty()
                || jPassword.getText().isEmpty()
                || jFullName.getText().isEmpty()
                || jAge.getText().isEmpty()
                || jGenderCombo.getSelectedItem().toString().equalsIgnoreCase("select")
                || jAddress.getText().isEmpty()
                || jMaritialCombo.getSelectedItem().toString().equalsIgnoreCase("select")
                || jPhoneNo.getText().isEmpty()
                || jDate.getDate()==null
                || jBloodGroupCombo.getSelectedItem().toString().equalsIgnoreCase("select") 
                || jPatientTypeCombo.getSelectedItem().toString().equalsIgnoreCase("select")) {
            JOptionPane.showMessageDialog(null, "Data Field is Empty",
                    "ERROR", JOptionPane.WARNING_MESSAGE);

        } else {
      
        String username = jUserName.getText();
        String password = jPassword.getText();
        String name = jFullName.getText();
        String age = jAge.getText();
        String gender = jGenderCombo.getSelectedItem().toString();
        String address = jAddress.getText();
        String maritial = jMaritialCombo.getSelectedItem().toString();
        String phone = jPhoneNo.getText();
        String blood = jBloodGroupCombo.getSelectedItem().toString();
        String patientType = jPatientTypeCombo.getSelectedItem().toString();
        Date date = jDate.getDate();
        
         List<Patient> chlist = new ArrayList<Patient>();
                   FileRead objch=new FileRead();
                chlist = objch.fileReadPatient();
                int check = 0;
                for (Patient a : chlist) {

                    if (username.equalsIgnoreCase(a.getUsername())&&!username.equalsIgnoreCase(chlist.get(patientListNumber).getUsername())) {
                        check = 1;
                    }
                }

                if (check == 1) {
                    JOptionPane.showMessageDialog(null, "Use Another Username");
                } else {
        Patient obj = new Patient(patientType, date,plist.get(patientListNumber).getDisease(),
                plist.get(patientListNumber).getMedicineName(), plist.get(patientListNumber).getDose(), 
                plist.get(patientListNumber).getTime(), plist.get(patientListNumber).getDiscription(),null, name, age, gender, address, maritial, phone, blood, username, password);
        
        FileUpdate fu = new FileUpdate();
        fu.fileUpdatePatient(patientListNumber, obj);
        JOptionPane.showMessageDialog(null, "Updated Successfully",
                "Success", JOptionPane.WARNING_MESSAGE);
        clear();
        patientListNumber=-1;c=0;}
    
        }
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void add5addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add5addMouseClicked
        RecpPanelAppointment pa=new RecpPanelAppointment();
        pa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add5addMouseClicked

    private void update4updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update4updateMouseClicked
        RecpPanelEdit pupdate=new RecpPanelEdit();
        pupdate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update4updateMouseClicked

    private void update5updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update5updateMouseClicked
        RecpPatientPanelAdd rppa=new RecpPatientPanelAdd();
        rppa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update5updateMouseClicked

    private void update6updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update6updateMouseClicked
        
    }//GEN-LAST:event_update6updateMouseClicked

    private void update7updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update7updateMouseClicked
        RecpPatientPanelRemove rppr=new RecpPatientPanelRemove();
        rppr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update7updateMouseClicked

    private void update8updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update8updateMouseClicked
        RecpPatientPanelList rppl=new RecpPatientPanelList();
        rppl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update8updateMouseClicked

    private void update9updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update9updateMouseClicked
        RecpPatientPanelSearch rpps=new RecpPatientPanelSearch();
        rpps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update9updateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecpPatientPanelUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecpPatientPanelUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecpPatientPanelUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecpPatientPanelUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecpPatientPanelUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add5;
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jAge;
    private javax.swing.JComboBox<String> jBloodGroupCombo;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JTextField jFullName;
    private javax.swing.JComboBox<String> jGenderCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMaritialCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jPassword;
    private javax.swing.JComboBox<String> jPatientTypeCombo;
    private javax.swing.JTextField jPhoneNo;
    private javax.swing.JTextField jSearch;
    private javax.swing.JButton jSearchButton;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JTextField jUserName;
    private javax.swing.JTextField name;
    private javax.swing.JLabel update4;
    private javax.swing.JLabel update5;
    private javax.swing.JLabel update6;
    private javax.swing.JLabel update7;
    private javax.swing.JLabel update8;
    private javax.swing.JLabel update9;
    // End of variables declaration//GEN-END:variables
}
